name: CI

on:
  push:
    branches:
    - main
    - develop

jobs:
  ci:
    name: Setup application enviroment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
      - name: get poetry
        run: |
          pip install poetry==1.1.5
      - name: install project dependencies
        run: |
          poetry install
      - name: Code quality checks
        run: |
          poetry run check-code-quality
