name: Tests
description: Runs application tests, linter and do import sort validations

on:
  push:
    branches:
    - main
    - develop

jobs:
  setup-enviroment:
    name: Setup application enviroment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
        scripts/setup_env
  code-quality-checks:
    name: Code quality checks
    steps:
      - name: Check code quality
        run: |
        poetry run check-code-quality